# pyproject.toml

include = [
    "Umshini/**",
]

[build-system]
requires      = ["setuptools>=61.0.0", "wheel", ]
build-backend = "setuptools.build_meta"

[project]
name = "umshini"
readme = "README.md"
description = "Umshini client for playing in MARL tournaments"
authors = [{ name = "Jordan K. Terry", email = "j.k.terry@swarmlabs.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
keywords = ["Reinforcement Learning", "game", "RL", "AI", "gym"]
requires-python = ">=3.7,<3.10"
dependencies = [
    "numpy>=1.19.0",
    "Cython>=0.29.21",
    "pettingzoo>=1.23.1" ,
    "supersuit==3.8.0",
    "halo",
    "colorama",
    "rlcard"
]
dynamic = ["version"]

[project.optional-dependencies]
classic = ["pettingzoo[classic]>=1.23.1"]
# llm = ["chatarena[umshini]>=0.1.12.4"] # TODO: add this back once chatarena fixes the issue on their end
llm = ["chatarena[umshini] @ git+https://github.com/chatarena/chatarena.git@d1680880f74da27ce3eaa6544c8cedf8d40f7a0c"]
all = ["pettingzoo[classic]>=1.23.1", "chatarena[umshini_requirements]>=0.1.12"]

[tool.setuptools.dynamic]
version = {attr = "umshini.__version__"}

[project.urls]
Homepage = "https://github.com/umshini/umshini"
